name: Deploy to Cloudflare Pages

on:
  release:
    types: [ published ]

jobs:
  publish:
    environment: public
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install wasm-tools
        run: dotnet workload install wasm-tools

      - name: Build Project
        run: dotnet publish -c Release -p:Version=${{ github.event.release.tag_name }} -o ./build-out NetTools/NetTools.csproj

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          directory: build-out/wwwroot
          branch: main
          wranglerVersion: '3'
